# Generated by Django 3.2.3 on 2021-06-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelinfo',
            old_name='max_value',
            new_name='max_price',
        ),
        migrations.AddField(
            model_name='modelinfo',
            name='max_volume',
            field=models.FloatField(null=True, verbose_name='Max Volume'),
        ),
    ]
