# Generated by Django 2.2.5 on 2021-05-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_type', models.CharField(max_length=1, verbose_name='CodeType')),
                ('code', models.CharField(db_index=True, max_length=4, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='CodeName')),
                ('memo', models.CharField(max_length=999, verbose_name='Description')),
            ],
            options={
                'db_table': 'trading_common_code',
                'ordering': ['c_type', 'code'],
            },
        ),
    ]
